
services:
  fpm:
    build:
      context: ./docker
      dockerfile: Dockerfile-php
    volumes:
      - ./:/var/www/project/:cached
    networks:
      - symfony

  nginx:
    build:
      context: ./docker
      dockerfile: Dockerfile-nginx
    volumes:
      - ./:/var/www/project/:cached
    ports:
      - 10302:80
    networks:
      - symfony

  database:
    image: postgres:${POSTGRES_VERSION:-16}
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    container_name: enteacher-database
    ports:
      - 5432:5432
    networks:
      - symfony

volumes:
  database_data:

networks:
  symfony: